---
- name: validate states on EOS devices using ANTA
  hosts: ACB
  gather_facts: false
  tasks:
    - name: validate states on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        # To enable ANTA
        use_anta: true
        # To save catalogs
        save_catalog: true
        skip_tests:
          - category: AvdTestHardware # Skip hardware related tests on cEOS devices
            tests:
              - VerifyEnvironmentPower
              - VerifyTemperature
              - VerifyEnvironmentCooling
              - VerifyTransceiversManufacturers
